### ISSUE TITLE
When exposing Nexus via NGINX Ingress on Kubernetes, users might see 413 request entity too large error

### ISSUE THREAD

**Issue by ricardozanini** [m88i/nexus-operator#129]
**Is your feature request related to a problem? Please describe.**
When users deploy Nexus and try to `mvn:deploy`, a 413 error might happen since the default NGINX Ingress is not correctly configured. Would be nice to deploy a ConfigMap with it to address this problem and let users to adjust the request size as their needs. Example:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  proxy-body-size: 10m
```

**Describe the solution you'd like**
Add a ConfigMap to address this problem, the configuration should not be modified/reconciled by the Operator

**Describe alternatives you've considered**
A workaround is to use NodePort instead or create a custom Ingress instead.

**Additional context**
Might be related: https://github.com/kubernetes/ingress-nginx/issues/4825
