### ISSUE TITLE
A fresh operator install on openshift okd can't start a nexus service

### ISSUE THREAD

**Issue by erkkikeranen** [m88i/nexus-operator#155]
**Describe the bug**
When I try to provision a nexus, the nexus pod tries to start, and fails:

```
pods "nexus3-7549c8c549-" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{200}: 200 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 200: must be in the ranges: [1000610000, 1000619999]]
```
Also, storage is in provisioning state.

**To Reproduce**
Provision a new nexus.

**Expected behavior**
A nexus is provisioned.

**Environment**
Openshift OKD 4.5.0-0.okd-2020-09-18-202631 running on Azure (Installer provisioned)
Nexus Operator 0.3.0 provided by m88i Labs

```
Client Version: 4.5.0-0.okd-2020-08-12-020541
Server Version: 4.5.0-0.okd-2020-09-18-202631
Kubernetes Version: v1.18.3
```

**Additional context**

YAML:
```yaml
spec:
  serviceAccountName: nexus3
  resources:
    limits:
      cpu: '2'
      memory: 2Gi
    requests:
      cpu: '1'
      memory: 2Gi
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 240
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 15
  useRedHatImage: false
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 240
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 15
  serverOperations: {}
  imagePullPolicy: Always
  automaticUpdate:
    disabled: true
  networking:
    expose: true
    exposeAs: Route
    tls:
      mandatory: true
  image: docker.io/sonatype/nexus3
  replicas: 1
  persistence:
    persistent: true
    storageClass: managed-premium
    volumeSize: 50Gi
status:
  deploymentStatus:
    conditions:
      - lastTransitionTime: '2020-09-21T12:31:13Z'
        lastUpdateTime: '2020-09-21T12:31:13Z'
        message: Deployment does not have minimum availability.
        reason: MinimumReplicasUnavailable
        status: 'False'
        type: Available
      - lastTransitionTime: '2020-09-21T12:31:13Z'
        lastUpdateTime: '2020-09-21T12:31:13Z'
        message: >-
          pods "nexus3-7549c8c549-" is forbidden: unable to validate against any
          security context constraint: [fsGroup: Invalid value: []int64{200}:
          200 is not an allowed group
          spec.containers[0].securityContext.securityContext.runAsUser: Invalid
          value: 200: must be in the ranges: [1000610000, 1000619999]]
        reason: FailedCreate
        status: 'True'
        type: ReplicaFailure
      - lastTransitionTime: '2020-09-21T12:31:11Z'
        lastUpdateTime: '2020-09-21T12:38:20Z'
        message: Created new replica set "nexus3-77ccb9c74f"
        reason: NewReplicaSetCreated
        status: 'True'
        type: Progressing
    observedGeneration: 6
    unavailableReplicas: 2
  nexusRoute: 'https://nexus3-nexus.apps.<omitted>'
  nexusStatus: Pending
  serverOperationsStatus:
    reason: Server does not have enough availble replicas
```
