### ISSUE TITLE
custom properties not applied to nexus.properties

### ISSUE THREAD

**Issue by rafaeltuelho** [m88i/nexus-operator#216]
**Describe the bug**
Tried to apply custom properties following this example https://github.com/m88i/nexus-operator/blob/main/examples/nexus3-centos-no-volume-custom-properties.yaml
but the operator just ignored my properties

**To Reproduce**
1. Add a new property 
```yaml
  properties:
    #https://issues.sonatype.org/browse/NEXUS-23205
    # script sample here: https://github.com/sonatype-nexus-community/nexus-scripting-examples
    nexus.scripts.allowCreation: "true"
```
to this sample https://github.com/m88i/nexus-operator/blob/main/examples/nexus3-centos-no-volume-custom-properties.yaml

2. create the nexus resource

**Expected behavior**
Have the ` nexus.scripts.allowCreation: "true"` applied to the `/nexus-data/etc/nexus.properties` file.

**Environment**
Openshift 4.7
nexus-operator v0.5.0

**Additional context**
