### ISSUE TITLE
Deployment Error on Openshift 4.8 - RuntimeException: AccessDeniedException: /nexus-data/etc/logback

### ISSUE THREAD

**Issue by nnachefski** [m88i/nexus-operator#223]
Hello,

I'm getting this error when attempting to deploy a nexus instance via the Community Operator from the catalog on Openshift 4.8

`1) [Guice/ErrorInjectingConstructor]: RuntimeException: AccessDeniedException: /nexus-data/etc/logback
`

Instance config is:

```
apiVersion: apps.m88i.io/v1alpha1
kind: Nexus
metadata:
  name: repo
  namespace: nexus
spec:
  automaticUpdate:
    disabled: true
  generateRandomAdminPassword: true
  image: registry.connect.redhat.com/sonatype/nexus-repository-manager
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 240
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 15
  networking:
    expose: true
    exposeAs: Route
    tls: {}
  persistence:
    persistent: true
    storageClass: managed-premium
    volumeSize: 200Gi
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 240
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 15
  replicas: 1
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 2Gi
  serverOperations: {}
  serviceAccountName: repo
  useRedHatImage: true
```

**Comment by ricardozanini** [comment]
Hi! Can you try mounting an empty volume dir in this path like was discussed here? https://github.com/m88i/nexus-operator/issues/222

**Comment by devent** [comment]
I hit the same bug in Kubernetes with NFS storage. The workaround works:

```
persistence:
  persistent: true
  storageClass: managed-nfs-storage
  volumeSize: 50Gi
  extraVolumes:
    - name: logback
      mountPath: /nexus-data/etc/logback
      emptyDir:
        medium: ""
```
